#' Produces sf dataframe with range polygon for a species
#'
#' @param dataframe an sf dataframe with a geometry column consisting of coordinates for each observation
#' @param species_col column in the dataframe identifying the species of each observation
#' @param species_to_map species to be mapped, wrap in quotes -> "Example sp."
#' @param background_map an sf object (map of a country, state, etc)
#' @param greatlakes_map an sf object of the Great Lakes
#' @param crs_map CRS to use for observation data and background maps
#'
#' @return a spatial dataframe
#' @export
#'
#' @examples 'RangeMap(frog_obs_iNat, Species, "Green Tree Frog", NorthAmerica, GreatLakes, 26917)'
RangeMap_df <- function(dataframe, species_col, species_to_map,
                      background_map, greatlakes_map, crs_map) {

  sf::sf_use_s2(FALSE)

  sf::st_crs(background_map)=4326
  sf::st_crs(greatlakes_map)=4326
  sf::st_crs(dataframe)=4326

  background_map.s <- background_map %>%
    sf::st_transform(., 5070)%>%
    dplyr::filter(country%in%c("CAN", "USA", "MEX"))%>%
    sf::st_simplify(., dTolerance = 3000)%>%
    sf::st_transform(., crs = crs_map)

  greatlakes_map.s <- greatlakes_map %>%
    sf::st_transform(., 5070)%>%
    dplyr::filter(NAME %in% c("Lake Michigan", "Lake Erie", "Lake Superior", "Lake Huron", "Lake", "Lake Ontario"))%>%
    sf::st_simplify(., dTolerance = 3000)%>%
    sf::st_transform(., crs = crs_map)

  Species_observations <- dataframe %>%
    dplyr::filter(species_col==species_to_map)%>%
    sf::st_transform(., crs = crs_map)

  Species_range <- Species_observations %>%
    dplyr::summarise()%>%
    sf::st_convex_hull()

  Range_landx <- sf::st_intersection(Species_range,
                                    sf::st_union(background_map.s))
  Range_land <- sf::st_difference(Range_landx,
                                    sf::st_union(greatlakes_map.s))

  sf::sf_use_s2(TRUE)

  return(Range_land)

}



#' Produce range map for a species
#'
#' @param dataframe an sf dataframe generated by TwoSpecies_df
#' @param background_map an sf object (map of a country, state, etc)
#' @param greatlakes_map an sf object of the Great Lakes
#' @param crs_map CRS to use for ranges and background maps
#' @param color_background fill color of background, defaults to white, wrap with ""
#' @param color_range fill color of range, defaults to green, wrap with ""
#' @param alpha_range transparency of range, defaults to 0.4
#'
#' @return ggplot object
#' @export
#'
#' @examples 'RangeMap_map(range, NorthAmerica, GreatLakes, 5070)'
RangeMap_map <- function(dataframe, background_map, greatlakes_map, crs_map,
                         color_background = "White", color_range = "forestgreen",
                         alpha_range = 0.4){

  sf::sf_use_s2(FALSE)

  sf::st_crs(background_map)=4326
  sf::st_crs(greatlakes_map)=4326
  sf::st_crs(dataframe)=4326

  background_map.s <- background_map %>%
    sf::st_transform(., 5070)%>%
    dplyr::filter(country%in%c("CAN", "USA", "MEX"))%>%
    sf::st_simplify(., dTolerance = 3000)%>%
    sf::st_transform(., crs = crs_map)

  greatlakes_map.s <- greatlakes_map %>%
    sf::st_transform(., 5070)%>%
    dplyr::filter(NAME %in% c("Lake Michigan", "Lake Erie", "Lake Superior", "Lake Huron", "Lake", "Lake Ontario"))%>%
    sf::st_simplify(., dTolerance = 3000)%>%
    sf::st_transform(., crs = crs_map)

  print("Formatted background maps.")

  dataframe.t <- dataframe %>%
    sf::st_transform(., crs = crs_map)

  sf::sf_use_s2(TRUE)

  box <- sf::st_bbox(dataframe.t)

  Map <- ggplot2::ggplot()+
    ggplot2::geom_sf(data = background_map.s,
                     fill = "white",
                     color = "grey41",
                     size = 0.10)+
    ggplot2::geom_sf(data = dataframe.t,
                     fill = color_range,
                     alpha = alpha_range,
                     color = "NA")+
    ggplot2::geom_sf(data = greatlakes_map.s,
                     fill = "lightskyblue",
                     color = NA)+
    ggplot2::coord_sf(xlim = c(box[1], box[3]),
                      ylim = c(box[2], box[4]))+
    ggplot2::theme(
      panel.grid.major = ggplot2::element_blank(),
      panel.background = ggplot2::element_rect(fill = color_background),
      panel.border = ggplot2::element_rect(fill = NA, size = 2))

  return(Map)
}
