#' Produces sf dataframe with range polygons for three species
#'
#' @param dataframe an sf dataframe with a geometry column consisting of coordinates for each observation
#' @param species_col column in the dataframe identifying the species of each observation
#' @param species1 1st species, wrap in quotes -> "Example sp."
#' @param species2 2nd species, wrap in quotes -> "Example sp."
#' @param background_map an sf object (map of a country, state, etc)
#' @param greatlakes_map an sf object of the Great Lakes
#' @param crs_map CRS to use for observation data and background maps
#' @param species3 3rd species, wrap in quotes -> "Example sp."
#'
#' @return a spatial dataframe
#' @importFrom magrittr %>%
#' @export
#'
#' @examples 'TwoSpecies_df(frog_obs, Species, "Green", "Frog", NorthAmerica, GreatLakes, 26917)'
ThreeSpecies_df <- function(dataframe, species_col, species1, species2, species3,
                              background_map, greatlakes_map, crs_map) {

  country <- NAME <- . <- NULL
  polygon <- range_valid <- NULL

  sf::sf_use_s2(FALSE)

  background_map.s <- background_map %>%
    sf::st_transform(., 26917)%>%
    dplyr::filter(country%in%c("CAN", "USA", "MEX"))%>%
    sf::st_simplify(., dTolerance = 3000)%>%
    sf::st_transform(., crs = crs_map)

  sf::st_crs(dataframe)=4269

  greatlakes_map.s <- greatlakes_map %>%
    sf::st_transform(., 26917)%>%
    dplyr::filter(NAME %in% c("Lake Michigan", "Lake Erie", "Lake Superior", "Lake Huron", "Lake", "Lake Ontario"))%>%
    sf::st_simplify(., dTolerance = 3000)%>%
    sf::st_transform(., crs = crs_map)

  print("Formatted background maps.")

  Range1 <- dataframe %>%
    dplyr::filter({{species_col}}==species1)%>%
    dplyr::summarise()%>%
    sf::st_convex_hull()%>%
    sf::st_transform(., crs = crs_map)

  Range2 <- dataframe %>%
    dplyr::filter({{species_col}}==species2)%>%
    dplyr::summarise()%>%
    sf::st_convex_hull()%>%
    sf::st_transform(., crs = crs_map)

  Range3 <- dataframe %>%
    dplyr::filter({{species_col}}==species3)%>%
    dplyr::summarise()%>%
    sf::st_convex_hull()%>%
    sf::st_transform(., crs = crs_map)

  Landx1 <- sf::st_intersection(Range1, sf::st_union(background_map.s))
  Land1 <- sf::st_difference(Landx1, sf::st_union(greatlakes_map.s))

  print(stringr::str_c("Created map for ", species1, ".", sep = ""))

  Landx2 <- sf::st_intersection(Range2, sf::st_union(background_map.s))
  Land2 <- sf::st_difference(Landx2, sf::st_union(greatlakes_map.s))

  print(stringr::str_c("Created map for ", species2, ".", sep = ""))

  Landx3 <- sf::st_intersection(Range3, sf::st_union(background_map.s))
  Land3 <- sf::st_difference(Landx3, sf::st_union(greatlakes_map.s))

  print(stringr::str_c("Created map for ", species3, ".", sep = ""))

  print(stringr::str_c("Creating combination maps for ", species1, ", ", species2, ", and ", species3, sep = ""))

  poly12 <- sf::st_difference(sf::st_intersection(Land1, Land2), Land3)
  poly13 <- sf::st_difference(sf::st_intersection(Land1, Land3), Land2)
  poly23 <- sf::st_difference(sf::st_intersection(Land2, Land3), Land1)
  poly1 <- sf::st_difference(Land1, sf::st_union(Land3, Land2))
  poly2 <- sf::st_difference(Land2, sf::st_union(Land3, Land1))
  poly3 <- sf::st_difference(Land3, sf::st_union(Land2, Land1))
  poly123 <- sf::st_intersection(sf::st_intersection(Land1, Land2), Land3)

  print("Done!")

  rawdf <- dplyr::tibble(
    polygon = c(poly1,
              poly2,
              poly3,
              poly12,
              poly13,
              poly23,
              poly123),
    range_item = c(
      species1,
      species2,
      species3,
      stringr::str_c(species1, " and ", species2, sep = ""),
      stringr::str_c(species1, " and ", species3, sep = ""),
      stringr::str_c(species2, " and ", species3, sep = ""),
      stringr::str_c(species1, ", ", species2, ", and ", species3, sep = "")))

  print("Preparing spatial dataframe.")

  Ranges.sf <- rawdf %>%
    dplyr::rowwise()%>%
    dplyr::mutate(lngth = length(polygon))%>%
    dplyr::mutate(range_valid = dplyr::case_when(
      lngth==0~"invalid",
      lngth==1~"valid"
    ))%>%
    dplyr::filter(range_valid=="valid")%>%
    # dplyr::select(-lngth, -range_valid)%>%
    tidyr::unnest(., polygon)%>%
    sf::st_as_sf(., geometry = .$polygon)%>%
    sf::st_transform(., crs = crs_map)%>%
    dplyr::select(-polygon)

  return(Ranges.sf)

}



#' Produces range map for three species
#'
#' @param dataframe an sf dataframe generated by ThreeSpecies_df
#' @param background_map an sf object (map of a country, state, etc)
#' @param greatlakes_map an sf object of the Great Lakes
#' @param crs_map CRS to use for ranges and background maps
#' @param color_background fill color of background, defaults to white, wrap with ""
#' @param alpha_range transparency of range, defaults to 0.4
#'
#' @return a ggplot object
#' @importFrom magrittr %>%
#' @export
#'
#' @examples 'TwoSpecies_map(ranges, NorthAmerica, GreatLakes, 5070)'
ThreeSpecies_map <- function(dataframe, background_map, greatlakes_map, crs_map,
                           color_background = "White", alpha_range = 0.4){

  country <- NAME <- . <- NULL
  polygon <- range_item <- NULL

  sf::sf_use_s2(FALSE)

  background_map.s <- background_map %>%
    sf::st_transform(., 26917)%>%
    dplyr::filter(country%in%c("CAN", "USA", "MEX"))%>%
    sf::st_simplify(., dTolerance = 3000)%>%
    sf::st_transform(., crs = crs_map)

  greatlakes_map.s <- greatlakes_map %>%
    sf::st_transform(., 26917)%>%
    dplyr::filter(NAME%in% c("Lake Michigan", "Lake Erie", "Lake Superior", "Lake Huron", "Lake", "Lake Ontario"))%>%
    sf::st_simplify(., dTolerance = 3000)%>%
    sf::st_transform(., crs = crs_map)

  print("Formatted background maps.")

  dataframe.t <- dataframe %>%
    sf::st_transform(., crs = crs_map)

  sf::sf_use_s2(TRUE)

  box <- sf::st_bbox(dataframe)

  print("Returning finished map!")

  Map <- ggplot2::ggplot()+
    ggplot2::geom_sf(data = background_map.s,
                     fill = "white",
                     color = "grey41",
                     size = 0.10)+
    ggplot2::geom_sf(data = dataframe.t,
                     alpha = alpha_range,
                     color = "NA",
                     ggplot2::aes(fill = range_item))+
    ggplot2::geom_sf(data = greatlakes_map.s,
                     fill = "lightskyblue",
                     color = NA)+
    ggplot2::coord_sf(xlim = c(box[1], box[3]),
                      ylim = c(box[2], box[4]))+
    ggplot2::theme(
      panel.grid.major = ggplot2::element_blank(),
      panel.background = ggplot2::element_rect(fill = color_background),
      panel.border = ggplot2::element_rect(fill = NA, size = 2))

  return(Map)
}
